# Temporary Bash context hook. @TOKEN@ and @KEY@ are generated by Emacs.
__gmx_context_install() {
    local declaration attribute item found=0
    [[ $- == *i* ]] || return 1
    if (( BASH_VERSINFO[0] < 4 || (BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] < 2) )); then
        builtin printf 'Mux context requires Bash 4.2+.\n' >&2; return 1
    fi
    declaration=$(builtin declare -p PROMPT_COMMAND 2>/dev/null) || declaration=
    attribute=${declaration#declare }; attribute=${attribute%% *}
    [[ $attribute != -*r* ]] || { builtin printf 'PROMPT_COMMAND is read-only.\n' >&2; return 1; }
    if [[ $attribute == -*a* ]] && (( BASH_VERSINFO[0] < 5 || (BASH_VERSINFO[0] == 5 && BASH_VERSINFO[1] < 1) )); then
        builtin printf 'Array PROMPT_COMMAND requires Bash 5.1+.\n' >&2; return 1
    fi
    __gmx_token='@TOKEN@'; __gmx_seq=0; __gmx_pid=$BASHPID; __gmx_uid=$EUID
    __gmx_host=$(command hostname) || return 1
    __gmx_user=$(command id -un) || return 1
    __gmx_emit() {
        local LC_ALL=C value encoded fields= byte i
        for value in "$@"; do
            encoded=
            for ((i=0; i<${#value}; i++)); do
                builtin printf -v byte '%02x' "'${value:i:1}"
                encoded+=$byte
            done
            fields+=" \"$encoded\""
        done
        builtin printf '\033]52;e;"ghostel-mux-context"%s\033\\' "$fields"
    }
    __gmx_report() {
        [[ $BASHPID == "$__gmx_pid" && $EUID == "$__gmx_uid" ]] || return 0
        __gmx_seq=$((__gmx_seq + 1))
        __gmx_emit 1 "$1" "$__gmx_token" "$__gmx_seq" "${2-}" "$__gmx_host" "$__gmx_user" "$EUID" "$BASHPID" "$PWD"
    }
    __gmx_prompt() {
        local status=$?
        __gmx_report prompt
        return "$status"
    }
    __gmx_probe() {
        local nonce
        if IFS= builtin read -r -s -N 32 -t 2 nonce && [[ $nonce != *[!0-9a-f]* && ${#nonce} == 32 ]]; then
            __gmx_report reply "$nonce"
        fi
    }
    local keymap
    for keymap in emacs-standard vi-insert vi-command; do
        if (( BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] < 3 )); then
            # Bash 4.2 bind -x only resolves one sub-keymap.
            builtin bind -m "$keymap" -x '"\C-x\C-^":__gmx_probe' || return 1
            builtin bind -m "$keymap" '"\e[99;@KEY@~":"\C-x\C-^"' || return 1
        else
            builtin bind -m "$keymap" -x '"\e[99;@KEY@~":__gmx_probe' || return 1
        fi
    done
    if [[ $attribute == -*a* ]]; then
        for item in "${PROMPT_COMMAND[@]}"; do
            [[ $item == __gmx_prompt ]] && found=1
        done
        (( found )) || PROMPT_COMMAND+=(__gmx_prompt)
    elif [[ $'\n'${PROMPT_COMMAND-}$'\n' != *$'\n__gmx_prompt\n'* ]]; then
        PROMPT_COMMAND="${PROMPT_COMMAND:+${PROMPT_COMMAND}$'\n'}__gmx_prompt"
    fi
}
__gmx_context_install
