;;; ghostel-mux-tests.el --- Integration tests -*- lexical-binding: t; -*-
(require 'ert)
(require 'ghostel-mux)

(defun ghostel-mux-test--wait (predicate &optional timeout)
  (let ((end (+ (float-time) (or timeout 4))))
    (while (and (not (funcall predicate)) (< (float-time) end))
      (accept-process-output nil 0.025))
    (should (funcall predicate))))
(defun ghostel-mux-test--text (p)
  (with-current-buffer (ghostel-mux--pane-buffer p)
    (or (ghostel--copy-all-text ghostel--term) "")))
(defun ghostel-mux-test--send (s)
  (let ((ghostel-mux--input-source (current-buffer))) (ghostel-send-string s)))

(defmacro ghostel-mux-test--with (&rest body)
  (declare (indent 0) (debug t))
  `(save-window-excursion
     (let ((ghostel-mux--sessions nil)
           (ghostel-mux--serial 0)
           (ghostel-mux--session-counters (make-hash-table :test #'eq))
           (ghostel-mux-scrollback-bytes (* 128 1024))
           (ghostel-mux-log-directory (make-temp-file "mux-ert-" t))
           (ghostel-mux-log-output t)
           (ghostel-mux-confirm-kill nil)
           (ghostel-mux-directory temporary-file-directory)
           (ghostel-shell '("/bin/bash" "--noprofile" "--norc"))
           (ghostel-shell-integration nil)
           (ghostel-term "xterm-256color")
           (ghostel-query-before-killing nil))
       (set-frame-parameter nil 'ghostel-mux-session nil)
       (unwind-protect
           (progn ,@body)
         (let ((ghostel-mux--closing t))
           (dolist (p (ghostel-mux--all-panes))
             (when (buffer-live-p (ghostel-mux--pane-buffer p))
               (kill-buffer (ghostel-mux--pane-buffer p)))))
         (set-frame-parameter nil 'ghostel-mux-session nil)
         (set-frame-parameter nil 'ghostel-mux-return-state nil)
         (delete-directory ghostel-mux-log-directory t)))))

(ert-deftest mux-sessions-window-layouts-and-independent-terminals ()
  (ghostel-mux-test--with
    (let* ((s1 (ghostel-mux-new-session "one"))
           (w1 (ghostel-mux--current-window))
           (p1 ghostel-mux--pane))
      (ghostel-mux-split-right)
      (should (= 2 (length (window-list))))
      (should-not (eq p1 ghostel-mux--pane))
      (should (cl-every #'ghostel-mux--pane-live-p (ghostel-mux--window-panes w1)))
      (ghostel-mux-new-window)
      (should (= 1 (length (window-list))))
      (ghostel-mux-previous-window)
      (should (= 2 (length (window-list))))
      (let ((s2 (ghostel-mux-new-session "two")))
        (should (= 1 (length (window-list))))
        (ghostel-mux "one")
        (should (eq s1 (ghostel-mux--current-session)))
        (should (= 2 (length (window-list))))
        (should-not (eq s1 s2))
        (should (= 4 (length (ghostel-mux--all-panes))))))))

(ert-deftest mux-zoom-survives-session-switch-and-keeps-sync ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (ghostel-mux-split-right)
    (ghostel-mux-split-below)
    (let ((w (ghostel-mux--current-window))
          (buffers (mapcar #'window-buffer (window-list))))
      (ghostel-mux-toggle-sync)
      (ghostel-mux-zoom)
      (should (= 1 (length (window-list))))
      (ghostel-mux-new-session "two")
      (ghostel-mux "one")
      (should (= 1 (length (window-list))))
      (should (ghostel-mux--window-sync w))
      (ghostel-mux-zoom)
      (should (= 3 (length (window-list))))
      (should (null (cl-set-difference buffers (mapcar #'window-buffer (window-list))))))))

(ert-deftest mux-broadcast-is-visible-only-and-resumes-after-unzoom ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "other")
    (let ((other ghostel-mux--pane))
      (ghostel-mux-new-session "one")
      (ghostel-mux-split-right)
      (let ((ps (copy-sequence (ghostel-mux--window-panes (ghostel-mux--current-window)))))
        (ghostel-mux-toggle-sync)
        (ghostel-mux-test--send "printf 'ONE_%s\\n' DELIVERY\n")
        (ghostel-mux-test--wait
         (lambda () (cl-every (lambda (p) (string-match-p "ONE_DELIVERY" (ghostel-mux-test--text p))) ps)))
        (dolist (p ps)
          (should (= 1 (cl-count-if (lambda (line) (string-match-p "ONE_DELIVERY" line))
                                    (split-string (ghostel-mux-test--text p) "\n")))))
        (should-not (string-match-p "ONE_DELIVERY" (ghostel-mux-test--text other)))
        (ghostel-mux-zoom)
        (should (string-match-p "SYNC PAUSED (LOCAL)" (ghostel-mux--status ghostel-mux--pane)))
        (ghostel-mux-test--send "printf 'SOLO_%s\\n' DELIVERY\n")
        (let ((active ghostel-mux--pane))
          (ghostel-mux-test--wait
           (lambda () (string-match-p "SOLO_DELIVERY" (ghostel-mux-test--text active))))
          (ghostel-mux-zoom)
          (ghostel-mux-test--send "printf 'AFTER_%s\\n' UNZOOM\n")
          (ghostel-mux-test--wait
           (lambda () (cl-every (lambda (p) (string-match-p "AFTER_UNZOOM" (ghostel-mux-test--text p))) ps)))
          (dolist (p (delq active (copy-sequence ps)))
            (should-not (string-match-p "SOLO_DELIVERY" (ghostel-mux-test--text p))))
          (should (string-match-p "SYNC:2" (ghostel-mux--status active))))))))

(ert-deftest mux-interactive-key-command-enters-broadcast-path ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (ghostel-mux-split-right)
    (ghostel-mux-toggle-sync)
    (let ((seen nil))
      (cl-letf (((symbol-function 'ghostel--write-pty)
                 (lambda (term bytes) (push (list term bytes) seen)))
                ((symbol-function 'ghostel--encode-key)
                 (lambda (term key mods &optional _utf8)
                   (should (equal key "c"))
                   (should (equal mods "ctrl"))
                   (push (list term "\x03") seen) t)))
        (call-interactively #'ghostel-send-C-c)
        (should (= 2 (length seen)))
        (should (= 2 (length (delete-dups (mapcar #'car seen)))))
        (should (cl-every (lambda (entry) (equal (cadr entry) "\x03")) seen))
        ;; An automatic/programmatic send is local even with SYNC enabled.
        (setq seen nil)
        (ghostel-send-string "PRIVATE")
        (should (= 1 (length seen)))))))

(ert-deftest mux-encoder-fallback-does-not-double-broadcast ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (ghostel-mux-split-right)
    (ghostel-mux-toggle-sync)
    (let ((seen nil) (encoded nil)
          (ghostel-mux--input-source (current-buffer)))
      (cl-letf (((symbol-function 'ghostel--encode-key)
                 (lambda (term &rest _) (push term encoded) nil))
                ((symbol-function 'ghostel--write-pty)
                 (lambda (term bytes) (push (list term bytes) seen))))
        (ghostel-send-key "up")
        (should (= 2 (length encoded)))
        (should (= 2 (length seen)))
        (should (= 2 (length (delete-dups (mapcar #'car seen)))))))))

(ert-deftest mux-paste-uses-each-terminal-encoder ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (ghostel-mux-split-right)
    (ghostel-mux-toggle-sync)
    (let ((seen nil)
          (kill-ring '("è Unicode\nsecond line")))
      (cl-letf (((symbol-function 'ghostel--encode-paste)
                 (lambda (term text) (push (cons term text) seen))))
        (call-interactively #'ghostel-yank)
        (should (= 2 (length seen)))
        (should (= 2 (length (delete-dups (mapcar #'car seen)))))
        (should (cl-every (lambda (x) (equal (cdr x) "è Unicode\nsecond line")) seen))))))

(ert-deftest mux-output-callbacks-and-auto-passwords-remain-local ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (ghostel-mux-split-right)
    (ghostel-mux-toggle-sync)
    (let ((seen nil) (ghostel-mux--input-source (current-buffer)))
      (cl-letf (((symbol-function 'ghostel--write-pty)
                 (lambda (term bytes) (push (list term bytes) seen))))
        (ghostel-mux--local-only (lambda () (ghostel-send-string "AUTO")))
        (should (= 1 (length seen)))))))

(ert-deftest mux-copy-is-persistent-and-never-deletes-output ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (ghostel-mux-copy-mode)
    (let ((inhibit-read-only t) (ghostel--inhibit-insert-forwarding t))
      (erase-buffer) (insert "alpha beta\ngamma\n"))
    (let ((original (buffer-string)) (transient-mark-mode t))
      (goto-char (point-min)) (push-mark (+ (point-min) 5) t t)
      (ghostel-mux-copy-selection)
      (should (equal (current-kill 0) "alpha"))
      (should (eq ghostel--input-mode 'copy))
      (should-not (region-active-p))
      (should (equal original (buffer-string)))
      (goto-char (point-min)) (push-mark (+ (point-min) 5) t t)
      (ghostel-mux-clear-selection)
      (should (eq ghostel--input-mode 'copy))
      (goto-char (point-min)) (push-mark (+ (point-min) 5) t t)
      (ghostel-mux-copy-selection-and-exit)
      (should (eq ghostel--input-mode 'semi-char)))))

(ert-deftest mux-prefix-and-copy-map-take-priority-in-char-mode ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (ghostel-char-mode) (ghostel-mux--refresh)
    (should (eq (key-binding (kbd "C-b")) #'ghostel-mux-prefix))
    (should (eq (key-binding (kbd "C-c")) #'ghostel-send-C-c))
    (ghostel-mux-copy-mode)
    (should (eq (key-binding (kbd "M-w")) #'ghostel-mux-copy-selection))
    (should (eq (key-binding (kbd "C-w")) #'ghostel-mux-copy-selection-and-exit))
    (should (eq (key-binding (kbd "C-g")) #'ghostel-mux-clear-selection))))

(ert-deftest mux-recording-retains-raw-bytes-and-records-hidden-output ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (let ((p ghostel-mux--pane))
      (ghostel-send-string "printf '\\033[31mRAW_%s\\033[0m\\n' MARKER\n")
      (ghostel-mux-new-window)
      (ghostel-mux-test--wait
       (lambda () (string-match-p "RAW_MARKER" (ghostel-mux-test--text p))))
      (ghostel-mux-flush-logs)
      (with-temp-buffer
        (insert-file-contents-literally (ghostel-mux--pane-log-file p))
        (should (string-match-p (regexp-quote "\e[31mRAW_MARKER\e[0m") (buffer-string))))
      (should (= #o600 (logand #o777 (file-modes (ghostel-mux--pane-log-file p))))))
    (should (cl-every (lambda (p)
                       (with-current-buffer (ghostel-mux--pane-buffer p)
                         (eq (process-type ghostel--process) 'real)))
                     (ghostel-mux--all-panes)))))

(ert-deftest mux-detach-restores-editor-and-keeps-processes ()
  (ghostel-mux-test--with
    (let ((before (window-buffer (selected-window))))
      (ghostel-mux-new-session "one")
      (let ((p ghostel-mux--pane))
        (ghostel-mux-detach)
        (should (eq before (window-buffer (selected-window))))
        (should (ghostel-mux--pane-live-p p))
        (ghostel-mux "one")
        (should (eq p ghostel-mux--pane))))))

(ert-deftest mux-closing-pane-cleans-membership-and-renumbers-windows ()
  (ghostel-mux-test--with
    (let ((s (ghostel-mux-new-session "one")))
      (ghostel-mux-split-right)
      (let ((p ghostel-mux--pane))
        (ghostel-mux-kill-pane)
        (ghostel-mux--reconcile s)
        (should-not (buffer-live-p (ghostel-mux--pane-buffer p)))
        (should (= 1 (length (ghostel-mux--window-panes (ghostel-mux--current-window)))))
        (should (= 1 (length (window-list)))))
      (ghostel-mux-new-window)
      (let ((remaining (ghostel-mux--current-window)))
        (ghostel-mux-previous-window)
        (ghostel-mux-kill-window)
        (ghostel-mux--reconcile s)
        (should (= 1 (ghostel-mux--window-number remaining)))
        (should (eq remaining (ghostel-mux--current-window)))))))

(ert-deftest mux-split-failure-preserves-layout-and-live-panes ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (let ((p ghostel-mux--pane))
      (cl-letf (((symbol-function 'ghostel-mux--create-terminal) (lambda (&rest _) (error "spawn failed"))))
        (should-error (ghostel-mux-split-right)))
      (should (= 1 (length (window-list))))
      (should (ghostel-mux--pane-live-p p))
      (should (= 1 (length (ghostel-mux--all-panes)))))))

(ert-deftest mux-names-do-not-escape-log-directory ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "../../strange;$(name)")
    (should (file-in-directory-p (ghostel-mux--pane-log-file ghostel-mux--pane)
                                ghostel-mux-log-directory))))

(ert-deftest mux-log-error-is-visible-and-does-not-stop-terminal ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (let ((p ghostel-mux--pane))
      (setf (ghostel-mux--pane-log-chunks p) '("data")
            (ghostel-mux--pane-log-file p) "/nonexistent/mux-test/output.log")
      (ghostel-mux--flush-log p)
      (should (ghostel-mux--pane-log-error p))
      (should (string-match-p "LOG ERROR" (ghostel-mux--status p)))
      (should (ghostel-mux--pane-live-p p)))))

(ert-deftest mux-real-keyboard-prefix-and-typing ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (execute-kbd-macro (kbd "C-b %"))
    (should (= 2 (length (ghostel-mux--all-panes))))
    (execute-kbd-macro (kbd "C-b y"))
    (should (ghostel-mux--window-sync (ghostel-mux--current-window)))
    (execute-kbd-macro "printf 'KEY_%s\\n' TEST\r")
    (ghostel-mux-test--wait
     (lambda () (cl-every (lambda (p) (string-match-p "KEY_TEST" (ghostel-mux-test--text p)))
                          (ghostel-mux--all-panes))))
    (execute-kbd-macro (kbd "C-b z"))
    (should (= 1 (length (window-list))))
    (execute-kbd-macro (kbd "C-b z"))
    (should (= 2 (length (window-list))))))

(ert-deftest mux-zoom-navigation-selects-another-live-buffer ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (ghostel-mux-split-right)
    (let ((before ghostel-mux--pane))
      (ghostel-mux-zoom)
      (ghostel-mux-next-pane)
      (should-not (eq before ghostel-mux--pane))
      (should (eq (current-buffer) (window-buffer (selected-window))))
      (ghostel-mux-next-pane)
      (should (eq before ghostel-mux--pane))
      (ghostel-mux-zoom)
      (should (= 2 (length (window-list)))))))

(ert-deftest mux-audit-outlives-scrollback-eviction ()
  (ghostel-mux-test--with
    (let ((ghostel-mux-scrollback-bytes 4096)) (ghostel-mux-new-session "one"))
    (let ((p ghostel-mux--pane))
      (ghostel-send-string "printf 'BEGIN_%s\\n' AUDIT; for i in {1..3000}; do printf 'line %s\\n' $i; done; printf 'END_%s\\n' AUDIT\n")
      (ghostel-mux-test--wait
       (lambda () (string-match-p "END_AUDIT" (ghostel-mux-test--text p))))
      (ghostel-mux-flush-logs)
      (should-not (string-match-p "BEGIN_AUDIT" (ghostel-mux-test--text p)))
      (with-temp-buffer
        (insert-file-contents-literally (ghostel-mux--pane-log-file p))
        (should (search-forward "BEGIN_AUDIT" nil t))
        (should (search-forward "END_AUDIT" nil t))))))

(ert-deftest mux-direct-writes-preserve-explicit-terminal-when-not-broadcasting ()
  (let ((ghostel-mux--input-source nil) (ghostel--term 'current) seen)
    (ghostel-mux--dispatch-write (lambda (term bytes) (setq seen (list term bytes)))
                                 'explicit "data")
    (should (equal seen '(explicit "data")))))

(ert-deftest mux-layout-cycling-keeps-all-pane-buffers ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (ghostel-mux-split-right)
    (ghostel-mux-split-below)
    (let ((buffers (mapcar #'ghostel-mux--pane-buffer (ghostel-mux--all-panes))))
      (dolist (layout '("horizontal" "vertical" "tiled"))
        (ghostel-mux-layout layout)
        (should (= 3 (length (window-list))))
        (should (null (cl-set-difference buffers (mapcar #'window-buffer (window-list)))))))))

(ert-deftest mux-mouse-word-line-and-clear-keep-copy-mode ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (ghostel-mux-copy-mode)
    (let ((inhibit-read-only t) (ghostel--inhibit-insert-forwarding t))
      (erase-buffer) (insert "alpha beta\ngamma\n"))
    (let* ((transient-mark-mode t)
           (pos (list (selected-window) 3 '(2 . 0) 0)))
      (ghostel-mux-copy-mouse-word (list 'double-mouse-1 pos))
      (should (equal (buffer-substring (region-beginning) (region-end)) "alpha"))
      (ghostel-mux-copy-mouse-line (list 'triple-mouse-1 pos))
      (should (equal (buffer-substring (region-beginning) (region-end)) "alpha beta\n"))
      (ghostel-mux-copy-mouse-click (list 'mouse-1 pos))
      (should-not (region-active-p))
      (should (eq ghostel--input-mode 'copy)))))

(ert-deftest mux-copy-drag-selection-persists-after-release ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (ghostel-mux-copy-mode)
    (let ((inhibit-read-only t) (ghostel--inhibit-insert-forwarding t))
      (erase-buffer) (insert "alpha beta\ngamma\n"))
    (let ((transient-mark-mode t))
      (ghostel-mouse-drag-or-set-region
       (list 'drag-mouse-1 (list (selected-window) 1 '(0 . 0) 0)
             (list (selected-window) 6 '(5 . 0) 100)))
      (should (region-active-p))
      (should (equal (buffer-substring (region-beginning) (region-end)) "alpha"))
      (should (eq ghostel--input-mode 'copy)))))

(ert-deftest mux-partial-delivery-turns-sync-off-without-retrying ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (ghostel-mux-split-right)
    (ghostel-mux-toggle-sync)
    (let ((w (ghostel-mux--current-window)) (calls 0)
          (ghostel-mux--input-source (current-buffer)))
      (ghostel-mux--dispatch (lambda () (cl-incf calls) (when (= calls 2) (error "write failed"))))
      (should (= calls 2))
      (should-not (ghostel-mux--window-sync w)))))

(ert-deftest mux-real-terminal-modes-encode-arrow-independently ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (let ((normal ghostel-mux--pane))
      (ghostel-send-string "printf '\\033[?1l'; stty raw -echo; printf 'NORMAL_%s\\n' READY; dd bs=1 count=3 2>/dev/null | od -An -tx1; stty sane\n")
      (ghostel-mux-split-right)
      (let ((application ghostel-mux--pane))
        (ghostel-send-string "printf '\\033[?1h'; stty raw -echo; printf 'APP_%s\\n' READY; dd bs=1 count=3 2>/dev/null | od -An -tx1; stty sane\n")
        (ghostel-mux-test--wait
         (lambda () (and (string-match-p "NORMAL_READY" (ghostel-mux-test--text normal))
                          (string-match-p "APP_READY" (ghostel-mux-test--text application)))))
        (ghostel-mux-toggle-sync)
        (let ((ghostel-mux--input-source (current-buffer))) (ghostel-send-key "up"))
        (ghostel-mux-test--wait
         (lambda () (and (string-match-p "1b 5b 41" (ghostel-mux-test--text normal))
                          (string-match-p "1b 4f 41" (ghostel-mux-test--text application)))))))))

(ert-deftest mux-native-backend-remains-available-without-recording ()
  (ghostel-mux-test--with
    (let ((ghostel-mux-log-output nil) (ghostel-use-native-pty t))
      (ghostel-mux-new-session "native"))
    (let ((p ghostel-mux--pane))
      (should-not (ghostel-mux--pane-log-file p))
      (should (eq (process-type ghostel--process) 'pipe))
      (ghostel-send-string "printf 'NATIVE_%s\\n' READY\n")
      (ghostel-mux-test--wait
       (lambda () (string-match-p "NATIVE_READY" (ghostel-mux-test--text p)))))))

(ert-deftest mux-legacy-creation-forces-fresh-buffer-and-restores-display ()
  (save-window-excursion
    (let ((before (current-buffer))
          (visible (window-buffer (selected-window)))
          created seen)
      (unwind-protect
          (cl-letf (((symbol-function 'ghostel-create) nil)
                    ((symbol-function 'ghostel)
                     (lambda (arg)
                       (setq seen (list arg ghostel-buffer-name)
                             created (generate-new-buffer ghostel-buffer-name))
                       (switch-to-buffer created)
                       created)))
            (should (eq (ghostel-mux--create-terminal "*legacy-test*") created))
            (should (equal seen '((4) "*legacy-test*")))
            (should (eq before (current-buffer)))
            (should (eq visible (window-buffer (selected-window)))))
        (when (buffer-live-p created) (kill-buffer created))))))

(ert-deftest mux-literal-prefix-is-encoded-on-each-pane ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (ghostel-mux-split-right)
    (ghostel-mux-toggle-sync)
    (let (seen)
      (cl-letf (((symbol-function 'ghostel--encode-key)
                 (lambda (term key mods &optional _utf8)
                   (push (list term key mods) seen) t)))
        (call-interactively #'ghostel-mux-send-prefix)
        (should (= 2 (length seen)))
        (should (cl-every (lambda (entry) (equal (cdr entry) '("b" "ctrl"))) seen))))))

(ert-deftest mux-command-minibuffer-accepts-text-and-followup-prompt ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (execute-kbd-macro (vconcat (kbd "C-b :") "new-session" (kbd "RET")
                               "new-session-test" (kbd "RET")))
    (should (equal (ghostel-mux--session-name (ghostel-mux--current-session))
                   "new-session-test"))
    (should (= 2 (length ghostel-mux--sessions)))
    (should-not (frame-parameter nil 'ghostel-mux-prefix))
    (should-not (eq overriding-terminal-local-map ghostel-mux-command-map))))

(ert-deftest mux-rename-minibuffer-accepts-prefix-command-letters ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (execute-kbd-macro (vconcat (kbd "C-b T") "new-pane" (kbd "RET")))
    (should (equal (ghostel-mux--pane-label ghostel-mux--pane) "new-pane"))
    (should (= 1 (length ghostel-mux--sessions)))
    (should (= 1 (length (ghostel-mux--all-panes))))))

(ert-deftest mux-meta-five-retiles-all-panes-even-from-zoom ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (ghostel-mux-split-right)
    (ghostel-mux-split-below)
    (ghostel-mux--select-pane (car (ghostel-mux--all-panes)))
    (ghostel-mux-split-below)
    (let ((buffers (mapcar #'ghostel-mux--pane-buffer (ghostel-mux--all-panes))))
      (ghostel-mux-layout "horizontal")
      (ghostel-mux-zoom)
      (execute-kbd-macro (kbd "C-b M-5"))
      (should-not (ghostel-mux--window-zoom-state (ghostel-mux--current-window)))
      (should (= 4 (length (window-list))))
      (should-not (cl-set-difference buffers (mapcar #'window-buffer (window-list))))
      (let ((widths (mapcar #'window-total-width (window-list)))
            (heights (mapcar #'window-total-height (window-list))))
        (should (<= (- (apply #'max widths) (apply #'min widths)) 1))
        (should (<= (- (apply #'max heights) (apply #'min heights)) 1))))))

(ert-deftest mux-copy-indicators-follow-actual-input-mode ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (let ((p ghostel-mux--pane))
      (execute-kbd-macro (kbd "C-b ["))
      (should (string-prefix-p " [COPY MODE]" (ghostel-mux--header p)))
      (should (string-match-p "\\[COPY MODE\\]" (ghostel-mux--status p)))
      (ghostel-mux-copy-selection)
      (should (string-prefix-p " [COPY MODE]" (ghostel-mux--header p)))
      (execute-kbd-macro (kbd "q"))
      (should-not (string-match-p "COPY MODE" (ghostel-mux--header p)))
      (should-not (string-match-p "COPY MODE" (ghostel-mux--status p)))
      ;; Also detect entry through Ghostel itself, before a refresh hook.
      (ghostel-copy-mode)
      (should (string-match-p "COPY MODE" (ghostel-mux--header p)))
      (ghostel-mux-copy-selection-and-exit)
      (should-not (string-match-p "COPY MODE" (ghostel-mux--status p))))))

(ert-deftest mux-refresh-removes-legacy-colors-preserving-user-remaps ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (let ((user-cookie (face-remap-add-relative 'default '(:height 1.1))))
      (setq ghostel-mux--face-cookie
            (face-remap-add-relative 'default 'ghostel-mux-terminal)
            ghostel-mux--face-state 'ghostel-mux-terminal)
      (ghostel-mux--refresh)
      (should-not ghostel-mux--face-cookie)
      (should-not (memq 'ghostel-mux-terminal (cdr (assq 'default face-remapping-alist))))
      (should (member (cdr user-cookie) (cdr (assq 'default face-remapping-alist))))
      (let ((expected (copy-tree face-remapping-alist)))
        (ghostel-mux-toggle-sync)
        (ghostel-mux--refresh)
        (should (equal expected face-remapping-alist))))))

(ert-deftest mux-zoom-keyboard-control-and-paste-target-only-visible-pane ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (ghostel-mux-split-right)
    (ghostel-mux-toggle-sync)
    (ghostel-mux-zoom)
    (let ((target ghostel--term) seen
          (kill-ring '("paste\nsecond line")))
      (cl-letf (((symbol-function 'ghostel--encode-key)
                 (lambda (term &rest _) (push term seen) t))
                ((symbol-function 'ghostel--encode-paste)
                 (lambda (term &rest _) (push term seen) t))
                ((symbol-function 'ghostel--write-pty)
                 (lambda (term &rest _) (push term seen))))
        (execute-kbd-macro (kbd "a C-c C-b C-b C-b ]"))
        (should (= 4 (length seen)))
        (should (cl-every (lambda (term) (eq term target)) seen))
        (ghostel-mux-next-pane)
        (setq target ghostel--term seen nil)
        (execute-kbd-macro (kbd "b C-b ]"))
        (should (= 2 (length seen)))
        (should (cl-every (lambda (term) (eq term target)) seen))))))

(ert-deftest mux-hidden-and-foreign-buffers-never-join-visible-broadcast ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "other")
    (let ((foreign (current-buffer)))
      (ghostel-mux-new-session "one")
      (let ((hidden (current-buffer)) (hidden-term ghostel--term)
            (view (selected-window)))
        (ghostel-mux-split-right)
        (ghostel-mux-split-below)
        (setq view (get-buffer-window hidden))
        (ghostel-mux-toggle-sync)
        (let ((w (ghostel-mux--current-window)) seen)
          (cl-letf (((symbol-function 'ghostel--write-pty)
                     (lambda (term &rest _) (push term seen))))
            (dolist (replacement (list (get-buffer-create "*scratch*") foreign))
              (set-window-buffer view replacement)
              (setq seen nil)
              (ghostel-mux-test--send "visible only")
              (should (= 2 (length seen)))
              (should-not (memq hidden-term seen))
              (should-not (memq (buffer-local-value 'ghostel--term foreign) seen))
              (should (string-match-p "SYNC:2" (ghostel-mux--sync-label w))))
            ;; Input invoked from a hidden source must never fan out either.
            (setq seen nil)
            (with-current-buffer hidden (ghostel-mux-test--send "local"))
            (should (equal seen (list hidden-term)))))))))

(ert-deftest mux-visible-broadcast-deduplicates-and-rechecks-targets ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (let ((first (current-buffer)))
      (ghostel-mux-split-right)
      (ghostel-mux-toggle-sync)
      (let ((duplicate (split-window-below)) seen)
        (set-window-buffer duplicate (current-buffer))
        (cl-letf (((symbol-function 'ghostel--write-pty)
                   (lambda (term &rest _) (push term seen))))
          (ghostel-mux-test--send "once")
          (should (= 2 (length seen)))
          (should (= 2 (length (delete-dups seen))))
          (delete-window duplicate)
          (setq seen nil)
          ;; The first recipient hides the other before its turn.
          (let ((ghostel-mux--input-source (current-buffer)))
            (ghostel-mux--dispatch
             (lambda ()
               (push (current-buffer) seen)
               (when-let ((win (get-buffer-window first)))
                 (set-window-buffer win (get-buffer-create "*scratch*"))))))
          (should (= 1 (length seen))))))))

(ert-deftest mux-process-exit-closes-pane-and-last-session-on-both-backends ()
  (dolist (native '(nil t))
    (ghostel-mux-test--with
      (let ((before (window-buffer (selected-window)))
            (ghostel-use-native-pty native)
            (ghostel-mux-log-output (not native)))
        (ghostel-mux-new-session "one")
        (let ((remaining (current-buffer)))
          (ghostel-mux-split-right)
          (let ((exiting (current-buffer))
                (log (ghostel-mux--pane-log-file ghostel-mux--pane)))
            (ghostel-send-string "printf 'FINAL_%s\\n' OUTPUT; exit\n")
            (ghostel-mux-test--wait
             (lambda () (and (not (buffer-live-p exiting))
                             (= 1 (length (ghostel-mux--all-panes)))
                             (= 1 (length (window-list))))))
            (should (eq remaining (window-buffer (selected-window))))
            (when log
              (should (with-temp-buffer (insert-file-contents log)
                                        (search-forward "FINAL_OUTPUT" nil t)))))
          (ghostel-send-string "exit\n")
          (ghostel-mux-test--wait
           (lambda () (and (null ghostel-mux--sessions)
                           (null (ghostel-mux--current-session))))))
        (should (eq before (window-buffer (selected-window))))))))

(ert-deftest mux-hidden-process-death-preserves-zoom-and-local-input ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (let ((hidden (current-buffer)))
      (ghostel-mux-split-right)
      (ghostel-mux-split-below)
      (ghostel-mux-toggle-sync)
      (ghostel-mux-zoom)
      (let ((visible (current-buffer)) (w (ghostel-mux--current-window)))
        (with-current-buffer hidden (ghostel-send-string "kill -KILL $$\n"))
        (ghostel-mux-test--wait
         (lambda () (and (not (buffer-live-p hidden))
                         (= 2 (length (ghostel-mux--window-panes w))))))
        (should (ghostel-mux--window-zoom-state w))
        (should (= 1 (length (window-list))))
        (should (eq visible (window-buffer (selected-window))))
        (should (= 1 (length (ghostel-mux--visible-panes w))))))))

(ert-deftest mux-native-prefix-exposes-full-key-sequences-to-emacs ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (dolist (mode '(ghostel-semi-char-mode ghostel-char-mode ghostel-copy-mode))
      (funcall mode)
      (ghostel-mux--refresh)
      (should (keymapp (key-binding (kbd "C-b"))))
      (should (eq (key-binding (kbd "C-b s")) #'ghostel-mux-select-session))
      (should (eq (key-binding (kbd "C-b M-5")) #'ghostel-mux-layout-tiled))
      (should (keymapp (key-binding (kbd "C-b g"))))
      (should (eq (key-binding (kbd "C-b g C-e")) #'ghostel-emacs-mode))
      (should (eq (key-binding (kbd "C-b g C-j")) #'ghostel-semi-char-mode))
      (should (equal (where-is-internal 'ghostel-mux-select-session nil t)
                     (vconcat (kbd "C-b s")))))))

(ert-deftest mux-ghostel-prefix-mode-switches-and-shares-user-bindings ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (execute-kbd-macro (kbd "C-b g C-e"))
    (should (eq ghostel--input-mode 'emacs))
    (execute-kbd-macro (kbd "C-b g C-j"))
    (should (eq ghostel--input-mode 'semi-char))
    (should (eq (key-binding (kbd "C-c")) #'ghostel-send-C-c))
    (execute-kbd-macro (kbd "C-b g M-d"))
    (should (eq ghostel--input-mode 'char))
    (execute-kbd-macro (kbd "C-b g C-t"))
    (should (eq ghostel--input-mode 'copy))
    (let* ((map (lookup-key ghostel-mode-map (kbd "C-c")))
           (old (lookup-key map (kbd "<f12>"))))
      (unwind-protect
          (progn
            (define-key map (kbd "<f12>") #'ghostel-clear-scrollback)
            (should (eq (key-binding (kbd "C-b g <f12>"))
                        #'ghostel-clear-scrollback)))
        (define-key map (kbd "<f12>") old)))))

(ert-deftest mux-which-key-discovers-both-native-prefixes ()
  (skip-unless (require 'which-key nil t))
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (let ((was-enabled which-key-mode))
      (unwind-protect
          (progn
            (which-key-mode 1)
            (dolist (entry '(("C-b" "ghostel-mux-toggle-sync" "ghostel-mux-select-session"
                              "ghostel-mux-window-1" "ghostel-mux-resize-left-1")
                             ("C-b g" "ghostel-emacs-mode" "ghostel-semi-char-mode")))
              (let ((bindings (prin1-to-string
                               (which-key--get-current-bindings (kbd (car entry))))))
                (dolist (name (cdr entry))
                  (should (string-match-p name bindings))))))
        (unless was-enabled (which-key-mode -1))))))

(ert-deftest mux-preview-cycles-layouts-without-attaching-or-capturing ()
  (ghostel-mux-test--with
    (let ((one (ghostel-mux-new-session "one")))
      (ghostel-mux-split-right)
      (ghostel-mux-split-below)
      (let ((two (ghostel-mux-new-session "two")))
        (ghostel-mux-split-right)
        (ghostel-mux-zoom)
        (ghostel-mux "one")
        (ghostel-mux--capture)
        (let* ((original (current-window-configuration))
               (anchor (selected-window))
               (state (ghostel-mux--session-preview-state (selected-frame) original))
               (one-state (ghostel-mux--window-state (ghostel-mux--session-current one)))
               (two-state (ghostel-mux--window-state (ghostel-mux--session-current two)))
               (serial ghostel-mux--serial))
          (unwind-protect
              (progn
                (set-frame-parameter nil 'ghostel-mux-preview t)
                (funcall state 'preview "two")
                (should (= 1 (length (window-list))))
                (should (window-live-p anchor))
                (should (eq one (ghostel-mux--current-session)))
                (should-not (ghostel-mux--session-frame two))
                (ghostel-mux--capture)
                (ghostel-mux--refresh)
                (should (eq one-state (ghostel-mux--window-state (ghostel-mux--session-current one))))
                (should (eq two-state (ghostel-mux--window-state (ghostel-mux--session-current two))))
                (funcall state 'preview "one")
                (should (= 3 (length (window-list))))
                (should (window-live-p anchor))
                (funcall state 'preview nil)
                (should (eq anchor (selected-window)))
                (should (= serial ghostel-mux--serial)))
            (set-frame-parameter nil 'ghostel-mux-preview nil)
            (set-window-configuration original)))))))

(ert-deftest mux-consult-session-selection-and-cancel-restore-ownership ()
  (skip-unless (require 'consult nil t))
  (ghostel-mux-test--with
    (let ((one (ghostel-mux-new-session "one")))
      (ghostel-mux-split-right)
      (let ((two (ghostel-mux-new-session "two")))
        (ghostel-mux "one")
        (let ((consult-preview-key 'any))
          (execute-kbd-macro (vconcat (kbd "C-b s") "two" (kbd "RET"))))
        (should (eq two (ghostel-mux--current-session)))
        (should-not (ghostel-mux--session-frame one))
        (should-not (frame-parameter nil 'ghostel-mux-preview))
        ;; Drive the same Consult state protocol and abort after a real layout preview.
        (cl-letf (((symbol-function 'consult--read)
                   (lambda (_table &rest options)
                     (let ((state (plist-get options :state)))
                       (funcall state 'preview "one")
                       (should (= 2 (length (window-list))))
                       (signal 'quit nil)))))
          (let (cancelled)
            (condition-case nil (ghostel-mux-select-session) (quit (setq cancelled t)))
            (should cancelled)))
        (should (eq two (ghostel-mux--current-session)))
        (should (= 1 (length (window-list))))
        (should-not (frame-parameter nil 'ghostel-mux-preview))))))

(ert-deftest mux-preview-blocks-terminal-input-and-defers-process-reconcile ()
  (ghostel-mux-test--with
    (let ((one (ghostel-mux-new-session "one")))
      (ghostel-mux-split-right)
      (ghostel-mux-toggle-sync)
      (let ((p ghostel-mux--pane) sent)
        (unwind-protect
            (progn
              (set-frame-parameter nil 'ghostel-mux-preview t)
              (cl-letf (((symbol-function 'ghostel--write-pty)
                         (lambda (&rest _) (setq sent t))))
                (should-error (ghostel-mux-test--send "never send") :type 'user-error)
                (should-not sent))
              (kill-buffer (ghostel-mux--pane-buffer p))
              (ghostel-mux--reconcile one)
              (should (frame-parameter nil 'ghostel-mux-preview-reconcile))
              (should (= 1 (length (ghostel-mux--window-panes (ghostel-mux--session-current one))))))
          (set-frame-parameter nil 'ghostel-mux-preview nil)
          (set-frame-parameter nil 'ghostel-mux-preview-reconcile nil)
          (ghostel-mux--reconcile one))
        (should (= 1 (length (window-list))))))))

(ert-deftest mux-status-distinguishes-selection-targets-and-local-input ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (let ((first ghostel-mux--pane))
      (ghostel-mux-split-right)
      (let ((second ghostel-mux--pane))
        (should (string-match-p "P2 SELECTED | SYNC OFF (LOCAL)" (ghostel-mux--status second)))
        (should (equal (ghostel-mux--pane-role first) "INACTIVE"))
        (ghostel-mux-toggle-sync)
        (should (string-match-p "SYNC:2 \\[P1,P2\\]" (ghostel-mux--status second)))
        (should (equal (ghostel-mux--pane-role first) "SYNC TARGET"))
        (set-frame-parameter nil 'ghostel-mux-prefix t)
        (should (string-match-p "SYNC:2" (ghostel-mux--status second)))
        (set-frame-parameter nil 'ghostel-mux-prefix nil)
        (ghostel-mux-zoom)
        (should (string-match-p "SYNC PAUSED (LOCAL).*ZOOM" (ghostel-mux--status second)))
        (should (equal (ghostel-mux--pane-role first) "INACTIVE"))
        (ghostel-mux-zoom)
        (ghostel-mux--select-pane first)
        (should (equal (ghostel-mux--pane-role first) "SELECTED"))
        (should (equal (ghostel-mux--pane-role second) "SYNC TARGET"))))))

(ert-deftest mux-render-uses-real-selection-not-redisplays-temporary-window ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (ghostel-mux-split-right)
    ;; Redisplay temporarily selects the window whose mode/header line it renders.
    (cl-letf (((symbol-function 'mode-line-window-selected-p) (lambda () nil)))
      (should (string-match-p "P2 INACTIVE" (car (ghostel-mux--render 'status))))
      (should-not (string-match-p "SELECTED" (car (ghostel-mux--render 'header)))))
    (cl-letf (((symbol-function 'mode-line-window-selected-p) (lambda () t)))
      (should (string-match-p "P2 SELECTED" (car (ghostel-mux--render 'status)))))))

(ert-deftest mux-preview-cancel-after-origin-dies-restores-emacs-workspace ()
  (skip-unless (require 'consult nil t))
  (ghostel-mux-test--with
    (let ((before (window-buffer (selected-window))))
      (ghostel-mux-new-session "one")
      (let ((origin (current-buffer)) (one (ghostel-mux--current-session)))
        (ghostel-mux-new-session "two")
        (ghostel-mux "one")
        (cl-letf (((symbol-function 'consult--read)
                   (lambda (_table &rest options)
                     (funcall (plist-get options :state) 'preview "two")
                     (kill-buffer origin)
                     (ghostel-mux--reconcile one)
                     (signal 'quit nil))))
          (condition-case nil (ghostel-mux-select-session) (quit nil)))
        (should-not (memq one ghostel-mux--sessions))
        (should-not (ghostel-mux--current-session))
        (should-not (frame-parameter nil 'ghostel-mux-preview))
        (should (= 1 (length ghostel-mux--sessions)))
        (should (eq before (window-buffer (selected-window))))))))

(ert-deftest mux-buffer-numbers-are-session-local-stable-across-windows-and-rename ()
  (ghostel-mux-test--with
    (let* ((one (ghostel-mux-new-session "one"))
           (first ghostel-mux--pane)
           (id (ghostel-mux--pane-id first))
           (log (ghostel-mux--pane-log-file first))
           (process ghostel--process))
      (should (equal (buffer-name) "*mux:one:1*"))
      (ghostel-mux-split-right)
      (should (equal (buffer-name) "*mux:one:2*"))
      (ghostel-mux-new-window)
      (should (equal (buffer-name) "*mux:one:3*"))
      (should (= 1 (ghostel-mux--pane-number ghostel-mux--pane)))
      (ghostel-mux-new-session "two")
      (should (equal (buffer-name) "*mux:two:1*"))
      (ghostel-mux-split-right)
      (should (equal (buffer-name) "*mux:two:2*"))
      (ghostel-mux "one")
      (ghostel-mux-kill-pane)
      (ghostel-mux--reconcile one)
      (ghostel-mux--select-pane first)
      (ghostel-mux-split-right)
      (should (equal (buffer-name) "*mux:one:4*"))
      (ghostel-mux-rename-session "renamed")
      (should (equal (buffer-name) "*mux:renamed:4*"))
      (should (equal (buffer-name (ghostel-mux--pane-buffer first)) "*mux:renamed:1*"))
      (should (= id (ghostel-mux--pane-id first)))
      (should (equal log (ghostel-mux--pane-log-file first)))
      (should (eq process (buffer-local-value 'ghostel--process (ghostel-mux--pane-buffer first))))
      (should (process-live-p process)))))

(ert-deftest mux-number-migration-preserves-identities-and-is-idempotent ()
  (ghostel-mux-test--with
    (let ((s (ghostel-mux-new-session "old")))
      (ghostel-mux-split-right)
      (ghostel-mux-new-window)
      (let* ((panes (ghostel-mux--all-panes))
             (ids (mapcar #'ghostel-mux--pane-id panes))
             (logs (mapcar #'ghostel-mux--pane-log-file panes))
             (serial ghostel-mux--serial))
        (clrhash ghostel-mux--session-counters)
        (dolist (p panes)
          (with-current-buffer (ghostel-mux--pane-buffer p)
            (setq ghostel-mux--session-number nil)
            (rename-buffer (format "*legacy:%d*" (ghostel-mux--pane-id p)))))
        (ghostel-mux--migrate-session-numbers)
        (should (equal '(1 2 3) (mapcar #'ghostel-mux--buffer-number panes)))
        (ghostel-mux--migrate-session-numbers)
        (should (= 3 (gethash s ghostel-mux--session-counters)))
        (should (= serial ghostel-mux--serial))
        (should (equal ids (mapcar #'ghostel-mux--pane-id panes)))
        (should (equal logs (mapcar #'ghostel-mux--pane-log-file panes)))
        (should (cl-every #'ghostel-mux--pane-live-p panes))
        (ghostel-mux-split-right)
        (should (equal (buffer-name) "*mux:old:4*"))))))

(ert-deftest mux-session-rename-preserves-unrelated-colliding-buffer ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "before")
    (let ((collision (get-buffer-create "*mux:after:1*")))
      (unwind-protect
          (progn
            (with-current-buffer collision (insert "keep this text"))
            (ghostel-mux-rename-session "after")
            (should-not (eq collision (current-buffer)))
            (should (equal (buffer-name collision) "*mux:after:1*"))
            (should (equal (with-current-buffer collision (buffer-string)) "keep this text"))
            (should (string-prefix-p "*mux:after:1*" (buffer-name))))
        (kill-buffer collision)))))

(ert-deftest mux-mixed-view-reports-scope-and-explicit-attach-switches-owner ()
  (ghostel-mux-test--with
    (let ((x (ghostel-mux-new-session "X")))
      (ghostel-mux-new-window)
      (let ((foreign (current-buffer))
            (p ghostel-mux--pane)
            (xw (ghostel-mux--current-window)))
        (ghostel-mux-previous-window)
        (ghostel-mux-new-session "Y")
        (ghostel-mux-split-right)
        (ghostel-mux-split-below)
        (let ((yw (ghostel-mux--current-window))
              (hidden (current-buffer))
              (view (selected-window)) seen)
          (set-window-buffer view foreign)
          (set-buffer foreign)
          (should (equal (ghostel-mux--pane-role p) "SELECTED · LOCAL"))
          (should (string-match-p "X:2/B2" (ghostel-mux--header p)))
          (should (string-match-p "ACTIVE Y:1" (ghostel-mux--header p)))
          (should (string-match-p "LOCAL | ACTIVE Y:1" (ghostel-mux--status p)))
          (execute-kbd-macro (kbd "C-b y"))
          (should (ghostel-mux--window-sync yw))
          (should-not (ghostel-mux--window-sync xw))
          (cl-letf (((symbol-function 'ghostel--write-pty)
                     (lambda (term &rest _) (push term seen))))
            (ghostel-mux-test--send "local")
            (should (equal seen (list (buffer-local-value 'ghostel--term foreign))))
            (ghostel-mux--select-pane (car (ghostel-mux--window-panes yw)))
            (setq seen nil)
            (ghostel-mux-test--send "group")
            (should (= 2 (length seen)))
            (should-not (memq (buffer-local-value 'ghostel--term foreign) seen))
            (should-not (memq (buffer-local-value 'ghostel--term hidden) seen)))
          (ghostel-mux-layout-tiled)
          (should (= 3 (length (ghostel-mux--visible-panes yw))))
          (should (get-buffer-window hidden))
          (should-not (get-buffer-window foreign))
          (set-window-buffer (selected-window) foreign)
          (set-buffer foreign)
          (execute-kbd-macro (kbd "C-b a"))
          (should (eq x (ghostel-mux--current-session)))
          (should (eq xw (ghostel-mux--current-window)))
          (should (eq foreign (window-buffer (selected-window))))
          (should (equal (ghostel-mux--pane-role p) "SELECTED"))
          (should (cl-every #'ghostel-mux--pane-live-p (ghostel-mux--all-panes))))))))

(ert-deftest mux-consult-window-keyboard-selects-exact-window-and-reverse-pane ()
  (skip-unless (require 'consult nil t))
  (ghostel-mux-test--with
    (let ((one (ghostel-mux-new-session "one")))
      (ghostel-mux-new-window)
      (ghostel-mux-rename-window "target")
      (let ((target (ghostel-mux--current-window)) (first ghostel-mux--pane))
        (ghostel-mux-split-right)
        (ghostel-mux-split-below)
        (let ((last ghostel-mux--pane))
          (ghostel-mux--select-pane first)
          (execute-kbd-macro (kbd "C-b O"))
          (should (eq last ghostel-mux--pane))
          (execute-kbd-macro (kbd "C-b o"))
          (should (eq first ghostel-mux--pane))
          (ghostel-mux-zoom)
          (execute-kbd-macro (kbd "C-b O"))
          (should (eq last ghostel-mux--pane))
          (should (= 1 (length (window-list))))
          (ghostel-mux-zoom))
        (ghostel-mux-previous-window)
        (ghostel-mux-new-session "two")
        (ghostel-mux "one")
        (let ((consult-preview-key 'any))
          (execute-kbd-macro (vconcat (kbd "C-b w") "one:2" (kbd "RET"))))
        (should (eq one (ghostel-mux--current-session)))
        (should (eq target (ghostel-mux--current-window)))
        (should (= 3 (length (window-list))))
        (should (eq ghostel--input-mode 'semi-char))
        (should-not (frame-parameter nil 'ghostel-mux-preview))))))

(ert-deftest mux-window-preview-cancel-keeps-origin-and-saved-window-selection ()
  (skip-unless (require 'consult nil t))
  (ghostel-mux-test--with
    (let* ((one (ghostel-mux-new-session "one"))
           (first (ghostel-mux--current-window)))
      (ghostel-mux-split-right)
      (ghostel-mux-new-window)
      (ghostel-mux-split-right)
      (ghostel-mux-zoom)
      (let* ((target (ghostel-mux--current-window))
             (target-buffer (current-buffer)))
        (ghostel-mux-previous-window)
        (ghostel-mux-new-session "two")
        (ghostel-mux-split-right)
        ;; A foreign terminal on screen does not change the attached session.
        (let ((foreign (current-buffer)))
          (ghostel-mux "one")
          (set-window-buffer (selected-window) foreign)
          (set-buffer foreign))
        (let ((origin (ghostel-mux--current-window))
              (views (mapcar #'window-buffer (window-list)))
              (saved (ghostel-mux--window-state target)) cancelled)
          (cl-letf (((symbol-function 'consult--read)
                     (lambda (names &rest options)
                       (should (= 2 (length names)))
                       (should (cl-every (lambda (n) (string-prefix-p "one:" n)) names))
                       (should (equal (plist-get options :prompt) "Window (one): "))
                       (funcall (plist-get options :state) 'preview
                                (cl-find-if (lambda (n) (string-prefix-p "one:2 " n)) names))
                       (should (eq origin (ghostel-mux--current-window)))
                       (should (eq first (ghostel-mux--session-current one)))
                       (should (eq (selected-frame) (ghostel-mux--session-frame one)))
                       (should (= 1 (length (window-list))))
                       (should (get-buffer-window target-buffer))
                       (with-current-buffer target-buffer
                         (should-error (ghostel-mux-test--send "blocked") :type 'user-error))
                       (ghostel-mux--capture)
                       (should (eq saved (ghostel-mux--window-state target)))
                       (signal 'quit nil))))
            (condition-case nil (ghostel-mux-select-window) (quit (setq cancelled t))))
          (should cancelled)
          (should (eq origin (ghostel-mux--current-window)))
          (should (equal views (mapcar #'window-buffer (window-list))))
          (should (eq first (ghostel-mux--session-current one)))
          (should-not (frame-parameter nil 'ghostel-mux-preview)))))))

(ert-deftest mux-window-selector-rejects-exited-candidate-and-supports-fallback ()
  (skip-unless (require 'consult nil t))
  (ghostel-mux-test--with
    (let* ((s (ghostel-mux-new-session "one"))
           (origin (ghostel-mux--current-window)))
      (ghostel-mux-new-window)
      (let ((dead (current-buffer)))
        (ghostel-mux-previous-window)
        (cl-letf (((symbol-function 'consult--read)
                   (lambda (names &rest options)
                     (let ((name (cl-find-if (lambda (n) (string-prefix-p "one:2 " n)) names)))
                       (funcall (plist-get options :state) 'preview name)
                       (kill-buffer dead)
                       (ghostel-mux--reconcile s)
                       name))))
          (should-error (ghostel-mux-select-window) :type 'user-error))
        (should (eq origin (ghostel-mux--current-window)))
        (should-not (frame-parameter nil 'ghostel-mux-preview))
        (let ((ghostel-mux-window-preview nil))
          (cl-letf (((symbol-function 'consult--read) (lambda (&rest _) (ert-fail "Consult used with preview disabled"))))
            (execute-kbd-macro (vconcat (kbd "C-b w") "one:1" (kbd "RET")))))
        (should (eq origin (ghostel-mux--current-window)))
        (ghostel-mux-detach)
        (should-error (ghostel-mux-select-window) :type 'user-error)))))

(ert-deftest mux-broadcast-marker-matches-delivery-and-pauses-with-local-input ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "foreign")
    (let ((foreign (current-buffer)))
      (ghostel-mux-new-session "one")
      (let ((first ghostel-mux--pane))
        (ghostel-mux-split-right)
        (ghostel-mux-split-below)
        (ghostel-mux-toggle-sync)
        (let* ((w (ghostel-mux--current-window))
               (source ghostel-mux--pane)
               (view (selected-window))
               (panes (ghostel-mux--window-panes w)) seen)
          (cl-letf (((symbol-function 'ghostel--write-pty)
                     (lambda (_term &rest _) (push ghostel-mux--pane seen))))
            (ghostel-mux-test--send "broadcast")
            (should (= 3 (length seen)))
            (dolist (p panes)
              (should (memq p seen))
              (should (ghostel-mux--sync-target-p p))
              (should (string-prefix-p " [S] " (ghostel-mux--header p))))
            (ghostel-mux-zoom)
            (setq seen nil)
            (ghostel-mux-test--send "zoom local")
            (should (equal seen (list source)))
            (should-not (cl-some #'ghostel-mux--sync-target-p panes))
            (ghostel-mux-zoom)
            (setq view (selected-window))
            (set-window-buffer (get-buffer-window (ghostel-mux--pane-buffer first)) (get-buffer-create "*scratch*"))
            (should-not (ghostel-mux--sync-target-p first))
            (should (ghostel-mux--sync-target-p source))
            (ghostel-mux-copy-mode)
            ;; Explicit paste can still broadcast from copy mode.
            (setq seen nil)
            (let ((kill-ring '("paste from copy mode")))
              (cl-letf (((symbol-function 'ghostel--encode-paste)
                         (lambda (&rest _) (push ghostel-mux--pane seen))))
                (ghostel-mux-paste)))
            (should (= 2 (length seen)))
            (dolist (p seen) (should (ghostel-mux--sync-target-p p)))
            (ghostel-mux-copy-exit)
            (set-window-buffer view foreign)
            (set-buffer foreign)
            (setq seen nil)
            (ghostel-mux-test--send "foreign local")
            (should (= 1 (length seen)))
            (should-not (cl-some #'ghostel-mux--sync-target-p panes))
            (should (ghostel-mux--window-sync w))))))))

(ert-deftest mux-marker-redisplay-uses-true-input-window-and-preserves-accent ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (ghostel-mux-split-right)
    (ghostel-mux-toggle-sync)
    (let ((p ghostel-mux--pane)
          (input (selected-window))
          (scratch (split-window-below))
          (comp-enable-subr-trampolines nil)
          (face (ghostel-mux--session-color (ghostel-mux--current-session))))
      (set-window-buffer scratch (get-buffer-create "*scratch*"))
      ;; Redisplay is drawing this terminal, but scratch is the true input window.
      (cl-letf (((symbol-function 'old-selected-window) (lambda () scratch))
                ((symbol-function 'mode-line-window-selected-p) (lambda () nil)))
        (should-not (string-match-p "\\[S\\]" (car (ghostel-mux--render 'header)))))
      (cl-letf (((symbol-function 'old-selected-window) (lambda () input))
                ((symbol-function 'mode-line-window-selected-p) (lambda () t)))
        (let ((text (car (ghostel-mux--render 'header))))
          (should (string-prefix-p " [S] ● one:" text))
          (should (memq 'ghostel-mux-broadcast-marker (get-text-property 1 'face text)))
          (should (memq face (get-text-property 7 'face text)))
          (should-not (eq face (get-text-property 10 'face text)))))
      (should (ghostel-mux--sync-target-p p)))))

(ert-deftest mux-consult-pane-keyboard-selects-buffer-within-zoom ()
  (skip-unless (require 'consult nil t))
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (let ((first ghostel-mux--pane))
      (ghostel-mux-split-right)
      (let ((second ghostel-mux--pane))
        (ghostel-mux-rename-pane "target")
        (ghostel-mux-split-below)
        (ghostel-mux-zoom)
        (let ((consult-preview-key 'any))
          (execute-kbd-macro (vconcat (kbd "C-b P") "2" (kbd "RET"))))
        (should (eq second ghostel-mux--pane))
        (should (eq second (ghostel-mux--window-zoom-pane (ghostel-mux--current-window))))
        (should (= 1 (length (window-list))))
        (should (eq ghostel--input-mode 'semi-char))
        (should-not (frame-parameter nil 'ghostel-mux-preview))
        (ghostel-mux-zoom)
        (should (= 3 (length (window-list))))
        (let ((ghostel-mux-pane-preview nil))
          (cl-letf (((symbol-function 'consult--read) (lambda (&rest _) (ert-fail "Consult called while disabled"))))
            (execute-kbd-macro (vconcat (kbd "C-b P") "1" (kbd "RET")))))
        (should (eq first ghostel-mux--pane))))))

(ert-deftest mux-pane-preview-cancel-restores-hidden-buffer-and-sync-scope ()
  (skip-unless (require 'consult nil t))
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (let ((hidden ghostel-mux--pane))
      (ghostel-mux-rename-pane "hidden")
      (ghostel-mux-split-right)
      (ghostel-mux-split-below)
      (set-window-buffer (get-buffer-window (ghostel-mux--pane-buffer hidden)) (get-buffer-create "*scratch*"))
      (ghostel-mux-toggle-sync)
      (ghostel-mux--capture)
      (let* ((w (ghostel-mux--current-window))
             (source ghostel-mux--pane)
             (saved (ghostel-mux--window-state w))
             (views (mapcar #'window-buffer (window-list))) cancelled sent)
        (cl-letf (((symbol-function 'consult--read)
                   (lambda (names &rest options)
                     (let ((state (plist-get options :state))
                           (name (cl-find-if (lambda (n) (string-match-p "hidden" n)) names)))
                       (funcall state 'preview name)
                       (should (= 3 (length (window-list))))
                       (should (get-buffer-window (ghostel-mux--pane-buffer hidden)))
                       (should (eq source (ghostel-mux--window-active w)))
                       (should-not (ghostel-mux--sync-target-p hidden))
                       (cl-letf (((symbol-function 'ghostel--write-pty) (lambda (&rest _) (setq sent t))))
                         (with-current-buffer (ghostel-mux--pane-buffer hidden)
                           (should-error (ghostel-mux-test--send "blocked") :type 'user-error)))
                       (should-not sent)
                       (ghostel-mux--capture)
                       (should (equal saved (ghostel-mux--window-state w)))
                       (signal 'quit nil)))))
          (condition-case nil (ghostel-mux-select-pane) (quit (setq cancelled t))))
        (should cancelled)
        (should (equal views (mapcar #'window-buffer (window-list))))
        (should-not (get-buffer-window (ghostel-mux--pane-buffer hidden)))
        (should (eq source ghostel-mux--pane))
        (should (ghostel-mux--window-sync w))
        (should-not (frame-parameter nil 'ghostel-mux-preview))))))

(ert-deftest mux-pane-selector-rejects-process-exit-during-preview ()
  (skip-unless (require 'consult nil t))
  (ghostel-mux-test--with
    (let ((s (ghostel-mux-new-session "one")) (first ghostel-mux--pane))
      (ghostel-mux-split-right)
      (ghostel-mux-rename-pane "exiting")
      (let ((dead (current-buffer)))
        (ghostel-mux--select-pane first)
        (cl-letf (((symbol-function 'consult--read)
                   (lambda (names &rest options)
                     (let ((name (cl-find-if (lambda (n) (string-match-p "exiting" n)) names)))
                       (funcall (plist-get options :state) 'preview name)
                       (kill-buffer dead)
                       (ghostel-mux--reconcile s)
                       name))))
          (should-error (ghostel-mux-select-pane) :type 'user-error))
        (should-not (frame-parameter nil 'ghostel-mux-preview))
        (should (eq first ghostel-mux--pane))
        (should (= 1 (length (window-list))))
        (should (ghostel-mux--pane-live-p first))))))

(ert-deftest mux-move-pane-reparents-with-live-process-and-log ()
  (ghostel-mux-test--with
    (let* ((s1 (ghostel-mux-new-session "one")) (w1 (ghostel-mux--current-window))
           (p1 ghostel-mux--pane))
      (ghostel-mux-split-right)
      (let* ((p ghostel-mux--pane) (buf (current-buffer)) (proc (get-buffer-process buf))
             (id (ghostel-mux--pane-id p)) (log (ghostel-mux--pane-log-file p))
             (s2 (ghostel-mux-new-session "two")) (w2 (ghostel-mux--current-window))
             (other ghostel-mux--pane))
        (setf (ghostel-mux--window-sync w1) t (ghostel-mux--window-sync w2) t)
        (ghostel-mux-move-pane w2 p)
        (should (eq (ghostel-mux--pane-window p) w2))
        (should (equal (ghostel-mux--window-panes w1) (list p1)))
        (should (equal (ghostel-mux--window-panes w2) (list other p)))
        (should (eq (get-buffer-process buf) proc))
        (should (process-live-p proc))
        (should (= id (ghostel-mux--pane-id p)))
        (should (equal log (ghostel-mux--pane-log-file p)))
        (should (= 2 (ghostel-mux--buffer-number p)))
        (should (equal (buffer-name buf) "*mux:two:2*"))
        (should-not (ghostel-mux--window-sync w1))
        (should-not (ghostel-mux--window-sync w2))
        (ghostel-mux-toggle-sync)
        (ghostel-mux-test--send "printf 'MOVED_%s\\n' OK\n")
        (ghostel-mux-test--wait
         (lambda () (and (string-match-p "MOVED_OK" (ghostel-mux-test--text p))
                         (string-match-p "MOVED_OK" (ghostel-mux-test--text other)))))
        (should-not (string-match-p "MOVED_OK" (ghostel-mux-test--text p1)))
        (ghostel-mux--attach s1)
        (should (= 1 (length (window-list))))
        (should (eq p1 ghostel-mux--pane))
        (ghostel-mux--attach s2)
        (should (= 2 (length (window-list))))))))

(ert-deftest mux-move-last-pane-to-session-creates-window-without-shell ()
  (ghostel-mux-test--with
    (let* ((source (ghostel-mux-new-session "source")) (p ghostel-mux--pane)
           (target (ghostel-mux-new-session "target"))
           (processes (mapcar (lambda (x) (get-buffer-process (ghostel-mux--pane-buffer x)))
                             (ghostel-mux--all-panes))))
      (ghostel-mux--attach source)
      (ghostel-mux-zoom)
      (ghostel-mux-move-pane target)
      (should-not (memq source ghostel-mux--sessions))
      (should (= 2 (length (ghostel-mux--session-windows target))))
      (should (eq target (ghostel-mux--current-session)))
      (should (eq p ghostel-mux--pane))
      (should (= 2 (length (ghostel-mux--all-panes))))
      (should (cl-every #'process-live-p processes))
      (should-not (ghostel-mux--window-zoom-state (ghostel-mux--pane-window p))))))

(ert-deftest mux-move-pane-same-session-keeps-buffer-number ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (let* ((p ghostel-mux--pane) (number (ghostel-mux--buffer-number p))
           (w (ghostel-mux-new-window)))
      (ghostel-mux-move-pane w p)
      (should (= number (ghostel-mux--buffer-number p)))
      (should (= 1 (length (ghostel-mux--session-windows (ghostel-mux--current-session)))))
      (should (= 2 (length (window-list)))))))

(ert-deftest mux-move-window-retains-zoom-processes-and-cleans-old-session ()
  (ghostel-mux-test--with
    (let* ((source (ghostel-mux-new-session "one")) (w (ghostel-mux--current-window)))
      (ghostel-mux-split-right)
      (ghostel-mux-toggle-sync)
      (ghostel-mux-zoom)
      (let* ((panes (copy-sequence (ghostel-mux--window-panes w)))
             (zoom (ghostel-mux--window-zoom-state w))
             (target (ghostel-mux-new-session "two")))
        (ghostel-mux--attach source)
        (ghostel-mux-move-window target)
        (should-not (memq source ghostel-mux--sessions))
        (should (eq target (ghostel-mux--window-session w)))
        (should (eq zoom (ghostel-mux--window-zoom-state w)))
        (should (= 1 (length (window-list))))
        (should-not (ghostel-mux--window-sync w))
        (should (cl-every #'ghostel-mux--pane-live-p panes))
        (should (equal '(2 3) (mapcar #'ghostel-mux--buffer-number panes)))
        (ghostel-mux-zoom)
        (should (= 2 (length (window-list))))))))

(ert-deftest mux-move-layout-failure-leaves-ownership-and-sync-intact ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (let* ((p ghostel-mux--pane) (w (ghostel-mux--current-window))
           (target (ghostel-mux-new-session "two")) (before (copy-sequence ghostel-mux--sessions)))
      (setf (ghostel-mux--window-sync w) t)
      (cl-letf (((symbol-function 'ghostel-mux--build-layout)
                 (lambda (&rest _) (error "No room"))))
        (should-error (ghostel-mux-move-pane target p)))
      (should (equal before ghostel-mux--sessions))
      (should (eq w (ghostel-mux--pane-window p)))
      (should (ghostel-mux--window-sync w))
      (should (ghostel-mux--pane-live-p p))
      (should (= 1 (length (ghostel-mux--session-windows target)))))))

(ert-deftest mux-move-rejects-expired-destination-and-preview ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (let ((p ghostel-mux--pane) (w (ghostel-mux--current-window)))
      (should-error (ghostel-mux-move-pane (ghostel-mux--make-session :name "dead") p)
                    :type 'user-error)
      (set-frame-parameter nil 'ghostel-mux-preview t)
      (unwind-protect
          (should-error (ghostel-mux-move-pane (ghostel-mux--current-session) p) :type 'user-error)
        (set-frame-parameter nil 'ghostel-mux-preview nil))
      (should (eq w (ghostel-mux--pane-window p))))))

(ert-deftest mux-auto-tile-reflows-after-exit-and-keeps-manual-sizes-until-change ()
  (ghostel-mux-test--with
    (let ((ghostel-mux-auto-tile t))
      (ghostel-mux-new-session "one")
      (ghostel-mux-split-right)
      (let ((w (ghostel-mux--current-window)))
        (window-resize nil -3 t)
        (let ((width (window-total-width)))
          (ghostel-mux--capture)
          (ghostel-mux-new-session "two")
          (ghostel-mux "one")
          (should (= width (window-total-width))))
        (ghostel-mux-split-below)
        (should (= 3 (length (window-list))))
        (let ((p ghostel-mux--pane))
          (ghostel-mux-test--send "exit\n")
          (ghostel-mux-test--wait (lambda () (not (buffer-live-p (ghostel-mux--pane-buffer p)))))
          (ghostel-mux--reconcile (ghostel-mux--window-session w))
          (should (= 2 (length (window-list))))
          (should (<= (abs (- (window-total-width (car (window-list)))
                              (window-total-width (cadr (window-list))))) 1)))))))

(ert-deftest mux-auto-tile-hidden-exit-retiled-on-return ()
  (ghostel-mux-test--with
    (let ((ghostel-mux-auto-tile t))
      (ghostel-mux-new-session "one")
      (ghostel-mux-split-right)
      (ghostel-mux-split-below)
      (let ((p ghostel-mux--pane))
        (ghostel-mux-new-session "two")
        (kill-buffer (ghostel-mux--pane-buffer p))
        (ghostel-mux "one")
        (should (= 2 (length (window-list))))
        (should-not (memq (ghostel-mux--pane-buffer p) (mapcar #'window-buffer (window-list))))))))

(ert-deftest mux-auto-tile-defers-while-zoomed ()
  (ghostel-mux-test--with
    (let ((ghostel-mux-auto-tile t))
      (ghostel-mux-new-session "one")
      (let ((hidden ghostel-mux--pane))
        (ghostel-mux-split-right)
        (ghostel-mux-split-below)
        (let ((active ghostel-mux--pane) (s (ghostel-mux--current-session)))
          (ghostel-mux-zoom)
          (kill-buffer (ghostel-mux--pane-buffer hidden))
          (ghostel-mux--reconcile s)
          (should (= 1 (length (window-list))))
          (should (eq active ghostel-mux--pane))
          (ghostel-mux-zoom)
          (should (= 2 (length (window-list)))))))))

(ert-deftest mux-auto-tile-disabled-preserves-explicit-split-direction ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (let ((w (ghostel-mux--current-window)))
      (puthash w nil ghostel-mux--auto-tiles)
      (ghostel-mux-split-below)
      (should (= (window-total-width (car (window-list))) (frame-width)))
      (should-not (ghostel-mux--auto-tile-p w))
      (ghostel-mux-toggle-auto-tile)
      (should (ghostel-mux--auto-tile-p w))
      (should (= 2 (length (window-list)))))))

(ert-deftest mux-tree-move-and-visit-restores-the-full-owning-layout ()
  (ghostel-mux-test--with
    (let* ((source (ghostel-mux-new-session "one")) (p ghostel-mux--pane)
           (target (ghostel-mux-new-session "two")) (w (ghostel-mux--current-window)))
      (unwind-protect
          (progn
            (ghostel-mux-tree)
            (should (derived-mode-p 'ghostel-mux-tree-mode))
            (should (string-match-p "one" (buffer-string)))
            (should (string-match-p "two" (buffer-string)))
            (ghostel-mux-move-pane w p)
            (should (ghostel-mux--tree-active-p))
            (should-not (memq source ghostel-mux--sessions))
            (should (string-match-p "P2 / B2" (buffer-string)))
            (goto-char (text-property-any (point-min) (point-max) 'ghostel-mux-node p))
            (ghostel-mux-tree-visit)
            (should (eq target (ghostel-mux--current-session)))
            (should (eq p ghostel-mux--pane))
            (should (= 2 (length (window-list))))
            (ghostel-mux-tree)
            (ghostel-mux-tree-quit)
            (should (= 2 (length (window-list)))))
        (set-frame-parameter nil 'ghostel-mux-tree-return nil)
        (when (get-buffer "*Ghostel Mux Tree*") (kill-buffer "*Ghostel Mux Tree*"))))))

(ert-deftest mux-tree-exit-of-last-process-removes-empty-session ()
  (ghostel-mux-test--with
    (let* ((s (ghostel-mux-new-session "one")) (p ghostel-mux--pane))
      (unwind-protect
          (progn
            (ghostel-mux-tree)
            (kill-buffer (ghostel-mux--pane-buffer p))
            (ghostel-mux--reconcile s)
            (should (ghostel-mux--tree-active-p))
            (should-not ghostel-mux--sessions)
            (should-not (ghostel-mux--current-session))
            (ghostel-mux-tree-quit))
        (set-frame-parameter nil 'ghostel-mux-tree-return nil)
        (when (get-buffer "*Ghostel Mux Tree*") (kill-buffer "*Ghostel Mux Tree*"))))))

(ert-deftest mux-tree-move-prompt-accepts-text-and-cancel-is-inert ()
  (ghostel-mux-test--with
    (ghostel-mux-new-session "one")
    (let* ((p ghostel-mux--pane) (old (ghostel-mux--pane-window p)))
      (ghostel-mux-new-session "two")
      (let ((target (ghostel-mux--current-window)))
        (unwind-protect
            (progn
              (ghostel-mux-tree)
              (goto-char (text-property-any (point-min) (point-max) 'ghostel-mux-node p))
              (execute-kbd-macro (kbd "m t w o C-g"))
              (should (eq old (ghostel-mux--pane-window p)))
              (execute-kbd-macro (kbd "m t w o SPC / SPC 1 : SPC s h e l l RET"))
              (should (ghostel-mux--tree-active-p))
              (should (eq target (ghostel-mux--pane-window p)))
              (ghostel-mux-tree-quit))
          (set-frame-parameter nil 'ghostel-mux-tree-return nil)
          (when (get-buffer "*Ghostel Mux Tree*") (kill-buffer "*Ghostel Mux Tree*")))))))

(ert-deftest mux-window-transfer-layout-failure-is-inert ()
  (ghostel-mux-test--with
    (let* ((source (ghostel-mux-new-session "one")) (w (ghostel-mux--current-window))
           (target (ghostel-mux-new-session "two")))
      (setf (ghostel-mux--window-sync w) t)
      (cl-letf (((symbol-function 'window-state-put) (lambda (&rest _) (error "Frame too small"))))
        (should-error (ghostel-mux-move-window target w)))
      (should (eq source (ghostel-mux--window-session w)))
      (should (memq w (ghostel-mux--session-windows source)))
      (should (ghostel-mux--window-sync w))
      (should (= 1 (length (ghostel-mux--session-windows target)))))))

(provide 'ghostel-mux-tests)
;;; ghostel-mux-tests.el ends here
